import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

interface EyeResult {
    predicted_class: number;
    stage: string;
    confidence: string;
    explanation: string;
    Note: string | null;
    Risk: string;
  }
  
  interface ApiResponse {
    left_image_result: EyeResult;
    right_image_result: EyeResult;
  }
const EyeAnalysisSection = ({ eye, data }: { eye: string; data: EyeResult }) => (
  <div className="mb-6">
    <h3 className="text-lg font-bold mb-2">{eye} Eye Analysis</h3>
    <div className="grid grid-cols-2 gap-4">
      <div>
        <p><strong>Stage:</strong> {data.stage}</p>
        <p><strong>Confidence:</strong> {data.confidence}</p>
        <p><strong>Risk:</strong> {data.Risk}</p>
      </div>
      <div>
        <p><strong>Explanation:</strong> {data.explanation}</p>
        {data.Note && <p><strong>Note:</strong> {data.Note}</p>}
      </div>
    </div>
  </div>
);

export const MedicalPDFReport = ({ patientId, apiData }: { patientId: string; apiData: ApiResponse }) => {
  return (
    <div className="p-8 max-w-4xl mx-auto bg-white">
      <h1 className="text-3xl font-bold mb-6 text-center">Diabetic Retinopathy Analysis Report</h1>
      <Separator className="my-4" />
      
      <div className="mb-6">
        <p><strong>Patient ID:</strong> {patientId}</p>
        <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Analysis Results</CardTitle>
        </CardHeader>
        <CardContent>
          <EyeAnalysisSection eye="Left" data={apiData.left_image_result} />
          <Separator className="my-4" />
          <EyeAnalysisSection eye="Right" data={apiData.right_image_result} />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <p>Based on the analysis results, we recommend the following:</p>
          <ul className="list-disc list-inside mt-2">
            <li>Schedule a follow-up appointment with your ophthalmologist.</li>
            <li>Continue monitoring blood sugar levels as advised by your physician.</li>
            <li>Maintain a healthy diet and exercise routine.</li>
            <li>Report any changes in vision immediately to your healthcare provider.</li>
          </ul>
        </CardContent>
      </Card>

      <div className="mt-8 text-sm text-gray-600">
        <p>This report is generated by an AI-assisted system and should be reviewed by a qualified healthcare professional. It does not constitute a medical diagnosis.</p>
      </div>
    </div>
  );
};